### ISSUE TITLE
how to get this conditional return statement to work

### ISSUE THREAD

**Issue by charlespedro** [JHU-DataViz-Summer16/week-2-js-dom#1]
Hi all,

I'm trying to filter on US states by region but it doesn't work. How does the conditional statement work with respect to printing a line based on a condition? For example, how do you say "print a line only if options.filtered equals "northeast"? I think probably the "return d.region..." part is wrong, but I'm not clear what it should be. 

```
  if (options.filtered) {
    if (options.filtered === 'northeast') {
        data = data.filter(function (d) {   return d.region === "Northeast" })
    } else if (options.filtered === 'south') {
      data = data.filter(function (d) { return d.region === "South"})
    } else if (options.filtered === 'midwest') {
      data = data.filter(function (d) { return d.region === "Midwest"})
    } else if (options.filtered === 'west') {
      data = data.filter(function (d) { return d.region === "West"})
    }
  }
```

Any suggestions are greatly appreciated. Thank you! 

Chuck

**Comment by cmgiven** [comment]
It's always obvious in hindsight. I notice that if I sort the results first, the filter buttons start working. Hmm, why's that, do you suppose?

Also, remember the difference between `=`, which assigns values to variables like `<-` in R, and `===`, which tests for equality. It's correct in the example code above, but not in your repo at the moment.
