### ISSUE TITLE
radio buttons

### ISSUE THREAD

**Issue by mike-bales** [JHU-DataViz-Summer16/week-2-js-dom#3]
I wanted to try adding functionality that allowed choosing to sort on one of two variables. I got it to work functionally but I found that the button for the sort category didn't stay active when I pressed which direction to sort in (asc or desc). So I tried to implement radio buttons from bootstrap (http://getbootstrap.com/javascript/#buttons-checkbox-radio) but they wouldn't work visually either. How can I get them to work?

**Comment by cmgiven** [comment]
One possibility is to use real radio buttons; these will automatically have their state updated by the browser. See the "Radio button input" section on this page: http://www.w3schools.com/html/html_forms.asp

Another solution is to set Bootstrap's `active` class on whatever the selected button is. This'll become much easier once we have D3 in our toolkit (starting tomorrow), but here's how I would do it with just Javascript: 2dd8b28

**Comment by cmgiven** [comment]
Also, be careful. Note that changing the candidate also changes the sort direction. These kind of interactions can lead to bugs if we aren't vigilant about keeping the browser state in sync with our Javascript state.
